<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Models\User;

class FormController extends Controller
{
    
    public function form()
    {
        return view('form');
    }


    public function store(Request $request)
    {
        $input = $request->all();
    
        // Hash the password
        $input['password'] = bcrypt($input['password']);
    
        User::create($input);
    
        // event(UserWasCreated::class);
        if (Auth::attempt($request->only('email', 'password'))) {
            return redirect()
                ->route('home.user')
                ->with('Welcome! Your account has been successfully created!');
        }
    
        // Redirect
        return redirect()
            // To the previous page (probably the one generated by a `getRegister` method)
            ->back()
            // And with the input data (so that the form will get populated again)
            ->withInput();
    }
   
}
